### ISSUE TITLE
Sorting feature is not working after update to 2023.5.4

### ISSUE THREAD

**Issue by OneComputerGuyWorking** [Kong/insomnia-docs#155] opened 2023-08-18 15:44 UTC
The default sorting of requests/folder within a Request Collection changed from ascending to descending by default and the sorting menu next to the search bar doesn't work (seems related to https://github.com/Kong/insomnia-docs/issues/153)

System info: 

Version: Insomnia 2023.5.4
Build date: 8/18/2023
OS: Darwin arm64 22.6.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64

**Comment by OneComputerGuyWorking** [comment] 2023-08-18 15:54
Furthermore, trying to sort anything, locks up the interface and doesn't allow sending requests or change to other collection/documents

**Comment by filfreire** [comment] 2023-08-18 15:56
duplicate of https://github.com/Kong/insomnia/issues/6288 and https://github.com/Kong/insomnia/issues/6284

**Closed by filfreire** 2023-08-18 15:56 UTC

**Comment by OneComputerGuyWorking** [comment] 2023-08-18 16:00
My apologies @filfreire, didn't realize I created the issue on the Docs GH
